### ISSUE TITLE
Cropping crops incorrectly

### ISSUE THREAD

**Issue by Tam** [verbb/image-resizer#18] opened 2017-01-12 12:21 UTC
Cropping an image produces a slightly unexpected result...

**Crop:**
[![Cropping](https://cloud.githubusercontent.com/assets/977594/21889369/81518b84-d8c0-11e6-94f0-7dc4358b6064.png)](https://www.fillmurray.com)

**Result:**
![fill_murray_1000x1000](https://cloud.githubusercontent.com/assets/977594/21889379/8e8b14a0-d8c0-11e6-9003-2ac8aa01261f.jpg)

ImageResizer v0.1.4  
Craft v2.6.2958

**Comment by engram-design** [comment] 2017-03-25 10:24
Hmm, I've tried this with a multitude of different images, types, sizes and cropping methods, and can't seem to reproduce. If you're still having issues, maybe we should catch up over Slack?

**Comment by engram-design** [comment] 2017-08-02 04:58
Might seem to be pulling up an old issue, but I think with the help of @moldedjelly this issue might be solved in the latest master. If you were using a remote asset store, this will likely have happened if the image uploaded was over 200px wide or hight.

**Comment by moldedjelly** [comment] 2017-08-02 05:13
just worked a bit more on it... and think this might be a bit better since it puts it into the assets/source folder and sets up nicely for the same folder structure in terms of originals and only fetches if necessary. This would replace the 3 lines 13-17 of ImageResizer_CropService.php

        $needToFetch = false;
        $path = $sourceType->getImageSourcePath($asset);
        if ($sourceType->isRemote()) {
          if (IOHelper::fileExists($path)) {
            $image = craft()->images->loadImage($path);
            if (($image->getWidth() < $asset->width || $image->getHeight() < $asset->height) && $sourceType->isRemote()) {
              $needToFetch = true;
            }
          } else {
            $needToFetch = true;
          }
          if ($needToFetch) {          
            $tempPath = $sourceType->getLocalCopy($asset);
            IOHelper::move($tempPath, $path);
          }
        }
        $folder = $asset->folder;
        $fileName = $asset->filename;

**Comment by engram-design** [comment] 2020-02-04 07:15
Closing - the Craft 2 version is no longer supported.

**Closed by engram-design** 2020-02-04 07:15 UTC
Labels: craft2
